"""add_user_classes_association

Revision ID: 61d0c5dab8ae
Revises: 86017b6a3fef
Create Date: 2026-06-25 13:44:54.232269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61d0c5dab8ae'
down_revision: Union[str, Sequence[str], None] = '86017b6a3fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_settings',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('school_start_time', sa.String(), nullable=True),
    sa.Column('school_end_time', sa.String(), nullable=True),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('half_day_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('enable_rfid', sa.String(), nullable=True),
    sa.Column('enable_biometric', sa.String(), nullable=True),
    sa.Column('auto_absent_time', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_settings_id'), 'attendance_settings', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_settings_school_id'), 'attendance_settings', ['school_id'], unique=True)
    op.create_table('rfid_cards',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rfid_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_rfid_cards_id'), 'rfid_cards', ['id'], unique=False)
    op.create_index(op.f('ix_rfid_cards_school_id'), 'rfid_cards', ['school_id'], unique=False)
    op.create_table('user_classes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'class_id')
    )
    op.create_foreign_key(None, 'classes', 'users', ['class_teacher_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.alter_column('subscription_plans', 'price',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('subscription_plans', 'price',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_table('user_classes')
    op.drop_index(op.f('ix_rfid_cards_school_id'), table_name='rfid_cards')
    op.drop_index(op.f('ix_rfid_cards_id'), table_name='rfid_cards')
    op.drop_table('rfid_cards')
    op.drop_index(op.f('ix_attendance_settings_school_id'), table_name='attendance_settings')
    op.drop_index(op.f('ix_attendance_settings_id'), table_name='attendance_settings')
    op.drop_table('attendance_settings')
    # ### end Alembic commands ###
