"""align_homework_module

Revision ID: 761a55716cd5
Revises: ffc32c152992
Create Date: 2026-06-25 14:22:48.477880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '761a55716cd5'
down_revision: Union[str, Sequence[str], None] = 'ffc32c152992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    submission_status = postgresql.ENUM('PENDING', 'SUBMITTED', 'GRADED', 'LATE', 'CORRECTION_REQUIRED', name='submission_status_enum', create_type=False)
    submission_status.create(op.get_bind(), checkfirst=True)
    
    op.add_column('homework_submissions', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('homework_submissions', sa.Column('status', submission_status, nullable=True))
    op.add_column('homework_submissions', sa.Column('submission_date', sa.Date(), nullable=True))
    op.add_column('homework_submissions', sa.Column('obtained_marks', sa.Integer(), nullable=True))
    op.add_column('homework_submissions', sa.Column('graded_by', sa.UUID(), nullable=True))
    op.add_column('homework_submissions', sa.Column('graded_at', sa.Date(), nullable=True))
    op.drop_constraint(op.f('homework_submissions_evaluated_by_fkey'), 'homework_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'homework_submissions', 'users', ['graded_by'], ['id'], ondelete='SET NULL')
    op.drop_column('homework_submissions', 'grade')
    op.drop_column('homework_submissions', 'evaluated_by')
    op.drop_column('homework_submissions', 'attachment_url')
    op.add_column('homeworks', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('homeworks', sa.Column('max_marks', sa.Integer(), nullable=True))
    op.add_column('homeworks', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('homeworks_created_by_fkey'), 'homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'homeworks', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.drop_column('homeworks', 'created_by')
    op.drop_column('homeworks', 'attachment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('homeworks', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.create_foreign_key(op.f('homeworks_created_by_fkey'), 'homeworks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('homeworks', 'teacher_id')
    op.drop_column('homeworks', 'max_marks')
    op.drop_column('homeworks', 'attachments')
    op.add_column('homework_submissions', sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('homework_submissions', sa.Column('evaluated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('homework_submissions', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('homework_submissions_evaluated_by_fkey'), 'homework_submissions', 'users', ['evaluated_by'], ['id'], ondelete='SET NULL')
    op.drop_column('homework_submissions', 'graded_at')
    op.drop_column('homework_submissions', 'graded_by')
    op.drop_column('homework_submissions', 'obtained_marks')
    op.drop_column('homework_submissions', 'submission_date')
    op.drop_column('homework_submissions', 'status')
    op.drop_column('homework_submissions', 'attachments')
    
    submission_status = postgresql.ENUM('PENDING', 'SUBMITTED', 'GRADED', 'LATE', 'CORRECTION_REQUIRED', name='submission_status_enum', create_type=False)
    submission_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
