"""add_user_audit_log

Revision ID: d8978fccf950
Revises: 61d0c5dab8ae
Create Date: 2026-06-25 14:17:38.397882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8978fccf950'
down_revision: Union[str, Sequence[str], None] = '61d0c5dab8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_audit_logs',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_TOGGLE', 'PASSWORD_CHANGE', name='user_audit_action_enum'), nullable=False),
    sa.Column('previous_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_audit_logs_id'), 'user_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_school_id'), 'user_audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_user_id'), 'user_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_audit_logs_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_school_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_id'), table_name='user_audit_logs')
    op.drop_table('user_audit_logs')
    # ### end Alembic commands ###
