"""add_attendance_correction_request

Revision ID: ffc32c152992
Revises: d8978fccf950
Create Date: 2026-06-25 14:18:47.556799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ffc32c152992'
down_revision: Union[str, Sequence[str], None] = 'd8978fccf950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_correction_requests',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('original_status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', name='attendance_status_enum', create_type=False), nullable=False),
    sa.Column('requested_status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', name='attendance_status_enum', create_type=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='correction_status_enum', create_type=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_correction_requests_id'), 'attendance_correction_requests', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_correction_requests_school_id'), 'attendance_correction_requests', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_correction_requests_user_id'), 'attendance_correction_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_correction_requests_user_id'), table_name='attendance_correction_requests')
    op.drop_index(op.f('ix_attendance_correction_requests_school_id'), table_name='attendance_correction_requests')
    op.drop_index(op.f('ix_attendance_correction_requests_id'), table_name='attendance_correction_requests')
    op.drop_table('attendance_correction_requests')
    # ### end Alembic commands ###
